# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 04:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.TextField(default=datetime.datetime(2017, 3, 11, 4, 38, 33, 151187, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='address',
            field=models.CharField(default=datetime.datetime(2017, 3, 11, 4, 38, 36, 734727, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='features',
            field=models.TextField(default=datetime.datetime(2017, 3, 11, 4, 38, 40, 847742, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='misc',
            field=models.TextField(default=datetime.datetime(2017, 3, 11, 4, 38, 42, 614444, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='municipality',
            field=models.CharField(default=datetime.datetime(2017, 3, 11, 4, 38, 44, 206686, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='province',
            field=models.CharField(default=datetime.datetime(2017, 3, 11, 4, 38, 46, 302563, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
