# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170311_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Destination')),
            ],
        ),
    ]
