# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 07:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='destination',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 3, 11, 7, 55, 35, 671205, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
