# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_remove_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 3, 11, 8, 27, 2, 145915, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
