# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='coords',
            field=models.TextField(default=datetime.datetime(2017, 3, 13, 3, 34, 50, 776926, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
