# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_destination_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('accessibility', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('safety_rating', models.TextField()),
                ('population', models.TextField()),
                ('known_for', models.TextField()),
                ('misc', models.TextField()),
                ('activities', models.TextField()),
                ('features', models.TextField()),
                ('coords', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
