# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_muni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muni',
            name='coords',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='muni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='muni',
            name='known_for',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='muni',
            name='population',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='muni',
            name='safety_rating',
            field=models.CharField(max_length=255),
        ),
    ]
