# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20170313_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muni',
            name='accessibility',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='coords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='known_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='misc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='population',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='muni',
            name='safety_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
