# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 03:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20170314_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='muni',
        ),
        migrations.AddField(
            model_name='destination',
            name='municipality',
            field=models.CharField(default=datetime.datetime(2017, 3, 14, 3, 59, 0, 423639, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
