# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20170314_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='municipality',
            new_name='muni',
        ),
    ]
