# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20170315_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Province'),
        ),
    ]
