# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20170314_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='muni',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
