# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_auto_20170316_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='kind',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muni',
            name='kind',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='kind',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
