# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_auto_20170314_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='muni',
        ),
    ]
