# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-20 02:53
from __future__ import unicode_literals

from django.db import migrations
import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_auto_20170320_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star_rating',
            field=likert_field.models.LikertField(blank=True, null=True),
        ),
    ]
