# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0023_remove_destination_muni'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='municipality',
            field=models.CharField(default='virac', max_length=255),
            preserve_default=False,
        ),
    ]
