# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='review',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
