# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-23 07:24
from __future__ import unicode_literals

import collection.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0025_auto_20170323_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(upload_to=collection.models.get_image_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
