# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_remove_muni_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
