# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-24 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_auto_20170324_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
