# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-14 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_auto_20170314_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='muni',
        ),
        migrations.AddField(
            model_name='destination',
            name='municipality',
            field=models.CharField(default='Virac', max_length=255),
            preserve_default=False,
        ),
    ]
