# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-09 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0044_review_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='savers',
            field=models.ManyToManyField(related_name='savers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='saves',
            field=models.IntegerField(default=0),
        ),
    ]
